export const styles = {
  container: {
    width: "500px",
    margin: "20px auto",
    padding: "20px", 
    border: "1px solid #ddd",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#f9f9f9",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 1000,
  },
  card: {
    padding: "15px",
    marginBottom: "15px", 
    border: "1px solid #e0e0e0",
    borderRadius: "8px",
    backgroundColor: "#fff",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "15px",
    padding: "5px 0",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  checkboxLabel: {
    color: "#333",
    fontSize: "14px",
    fontWeight: "500" as const,
  },
  selectGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    color: "#1a73e8",
    fontSize: "14px",
    marginBottom: "5px",
  },
  select: {
    width: "100%",
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
    backgroundColor: "#fff",
  },
  contentSection: {
    padding: "15px",
    backgroundColor: "#fff",
    borderRadius: "4px",
    border: "1px solid #e0e0e0",
  },
  inputGroup: {
    marginBottom: "15px",
  },
  input: {
    width: "100%",
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
  },
  inputWithText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  inputPrefix: {
    color: "#666",
    fontSize: "14px",
    minWidth: "45px",
  },
  inputWithPrefix: {
    flex: 1,
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "space-around",
    marginTop: "20px",
  },
  okBtn: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "8px 16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  closeBtn: {
    backgroundColor: "#007bff",
    color: "#fff",
    padding: "8px 16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  infoText: {
    color: "#666",
    fontSize: "14px",
    lineHeight: "1.5",
    padding: "10px",
    backgroundColor: "#f8f9fa",
    borderRadius: "4px",
    border: "1px solid #e0e0e0",
  },
  
  contentSection: {
    padding: "15px",
    backgroundColor: "#fff",
    borderRadius: "4px",
    marginTop: "15px",
  }
};