export const styles = {
  container: {
    width: "400px",
    margin: "20px auto",
    padding: "20px", 
    border: "1px solid #ddd",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#f9f9f9",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 1000,
  },
  card: {
    padding: "15px",
    marginBottom: "15px", 
    border: "1px solid #e0e0e0",
    borderRadius: "8px",
    backgroundColor: "#fff",
  },
  heading: {
    fontWeight: "bold" as const,
    color: "#000",
    marginBottom: "10px",
  },
  inputGroup: {
    display: "flex",
    justifyContent: "space-between",
  },
  label: {
    display: "block",
    color: "#1a73e8",
    fontSize: "14px",
    marginBottom: "5px",
  },
  input: {
    width: "100%",
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
  },
  infoText: {
    color: "#ff6600",
    fontSize: "12px",
    margin: "10px 0",
    textAlign: "center" as const,
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "space-around",
    marginTop: "10px",
  },
  okBtn: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "8px 16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  deleteBtn: {
    backgroundColor: "#dc3545",
    color: "#fff",
    padding: "8px 16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  closeBtn: {
    backgroundColor: "#007bff",
    color: "#fff",
    padding: "8px 16px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
};
